name: firebasetest
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.5.0
  firebase_auth: ^3.0.2
  cloud_firestore: ^2.5.0
  provider: ^6.0.0
  onboarding: ^2.1.0
  cupertino_icons: ^1.0.0
  flutter_easyloading: ^3.0.0
  expandable_text: ^2.2.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/web_hi_res_1024.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/web_hi_res_1024.png"


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - res/userinfo/
  fonts:
    - family: Stix
      fonts:
        - asset: res/fonts/static/STIXTwoText-Regular.ttf
        - asset: res/fonts/static/STIXTwoText-Bold.ttf
          weight: 800
        - asset: res/fonts/static/STIXTwoText-Italic.ttf
          style: italic

